#!/usr/bin/env bash
# Bash script that will display information about subdomains
# shellcheck disable=SC2086
domain_info(){
	dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -1 | sed "s/.$2./ /g" | awk '{print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]
then
domain_info "$2" "$1"
elif [ "$#" -eq 1 ]
then
domain_info "www" "$1"
domain_info "lb-01" "$1"
domain_info "web-01" "$1"
domain_info "web-02" "$1"
fi
