#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www
domain_cfg()
{

	result=$(dig "$1.$2" | grep -A1 'ANSWER SECTION'| tail -1 | tr '\t' ' ')
	ip=$(echo "$result" | cut -d ' ' -f5)
	register=$(echo "$result" | cut -d ' ' -f4)
#echo "$ip"
#	echo "$register"
	echo "$1 $register $ip" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3}'	
}
# domain_cfg  $2 $1
if [ $# -eq 1 ]
then 
	domain_cfg "www" $1
	domain_cfg "lb-01" $1
	domain_cfg "web-01" $1
	domain_cfg "web-02" $1
elif [ $# -eq 2 ]
then
	domain_cfg $2 $1
fi
