#!/usr/bin/env bash
#  Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
# be listening on port 80
sudo ufw allow "Nginx HTTP"
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# Start Nginx
sudo service nginx start
