#!/usr/bin/env bash
#  Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
# be listening on port 80
sudo ufw allow "Nginx HTTP"
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# change line
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=wDjeBNv6ip0 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
# change line
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
# change line
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
# Start Nginx
sudo service nginx restart
