#!/usr/bin/env bash
#This is a script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
i=1
while [ $i -lt 13 ]
do
	j=1
	echo "Hour: $i"
	while [ $j -lt 60 ]
	do
		echo $j
		let j+=1
	done
	let i+=1
done
