#!/usr/bin/env bash
#This is a scrip script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed 

ls="$(ls)"
for i in $ls
do
	echo "$i" | cut -d "-" -f2
done
